# Site settings
title: 文光小筑
subtitle: 差不多就是差很多
description: 他山之石，可以攻玉。
baseurl: "" # the subpath of your site, /nanwenguang
url: "http://yourdomain.com" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
author: nwg
email: wenguang.nan.cs@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins: [jekyll-paginate]
markdown: kramdown

# Pageinate settings
paginate: 7 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 关于
    directory: about/
    icon: icon-about
  # - page: 历史
  #   directory: history/
  #   icon: icon-history
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/
